### ISSUE TITLE
Routing broken in latest (~March 14th) iteration?

### ISSUE THREAD

**Issue by cdcme** [twostraws/HackingWithReact#2]
Steps to reproduce:
1. Clone, npm i, webpack-dev-server
2. Navigate to http://localhost:8080
3. Click the react link
4. Expect the react feed to load
5. Replace /react with /react-native in the address bar & hit Enter
6. Expect react native feed to load, but note that it does not

This just worked yesterday for me (I have links to /react, /react-native, and /jest on each page) and after updating this morning, it's no longer working. What has changed? I know a couple of dependencies were upgraded, could that be the issue?

I confirmed this in both my own app and a fresh clone of the author's (this) app.

**Edit:** I just found that if you follow the instructions to reproduce listed above, then click in the address bar and hit Enter _again_, the page reloads, loading the appropriate feed. It seems like something isn't getting fired when the user navigates to one of the feed pages for the first time for some reason.

**Comment by cdcme** [comment]
You can see the behavior demonstrated [in this screencast](http://screencast.com/t/ycomhnbc0nUe).

**Comment by twostraws** [comment]
This feels like an unexpected feature in the previous release rather than something broken in the update. That is, I wasn't aware this behaviour even worked previously, and I'm not surprised it doesn't work now.

React Router should(!) only be mounting a component once. If the component doesn't change but its props do (if the user changed the URL by hand, in your case), to the best of my knowledge React Router ought not to be calling `componentWillMount()` again because nothing is being mounted. Instead, you should use `componentWillReceiveProps()` or `componentDidUpdate()` to force a re-fetch of the feeds.

I would imagine that React Router 1.x (used before yesterday) was a bit more slack about this than 2.x (used from yesterday), which is what's causing your problem.

If you wanted the old behaviour back, you would probably want something like this:

```
componentWillMount() {
    this.fetchAll();
}

componentWillReceiveProps(newProps) {
    this.fetchAll();
}

fetchAll() {
    this.fetchFeed('commits');
    this.fetchFeed('forks');
    this.fetchFeed('pulls');
}
```

Give that a try and let me know if it solves your problem.

**Comment by cdcme** [comment]
Ha! Interesting... I'm not sure why that worked before but this explanation makes perfect sense. Thanks.

**Comment by cdcme** [comment]
Yeah, @twostraws, that did the trick. Interesting little puzzle, thanks!

**Comment by twostraws** [comment]
Glad to hear it! I'll think on this some more; I might modify the book to explain this in case others hit the same thing.
